[conf]
default-lang = "en"

[lang.fr]
theorem = "Théorème"
lemma = "Lemme"
corollary = "Corollaire"
remark = "Remarque"
definition = "Définition"
example = "Exemple"
exercise = "Exercice"
notation = "Notation"
proof = "Démonstration"
axiom = "Axiome"
proposition = "Proposition"
problem = "Problème"
conclusion = "Conclusion"
property = "Propriété"
solution = "Solution"
tip = "Conseil"
conjecture = "Conjecture"
caution = "Attention"
question = "Question"

[lang.de]
theorem = "Satz"
lemma = "Lemma"
corollary = "Korollar"
remark = "Bemerkung"
definition = "Definition"
example = "Beispiel"
exercise = "Übung"
notation = "Notation"
proof = "Beweis"
axiom = "Axiom"
proposition = "Proposition"
problem = "Problem"
conclusion = "Schlussfolgerung"
property = "Eigenschaft"
solution = "Lösung"
tip = "Hinweis"
conjecture = "Vermutung"
caution = "Vorsicht"
question = "Frage"


[lang.en]
theorem = "Theorem"
lemma = "Lemma"
corollary = "Corollary"
remark = "Remark"
definition = "Definition"
example = "Example"
exercise = "Exercise"
notation = "Notation"
proof = "Proof"
axiom = "Axiom"
proposition = "Proposition"
problem = "Problem"
conclusion = "Conclusion"
property = "Property"
solution = "Solution"
tip = "Tip"
conjecture = "Conjecture"
caution = "Caution"
question = "Question"
